apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-manual-testing-existing-default
  janus-idp.io/tekton: chatbot-manual-testing-existing-default
  backstage.io/kubernetes-id: chatbot-manual-testing-existing-default
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: chatbot-manual-testing-existing-default
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
